### ISSUE TITLE
[BUG] - Extension requires a specific version of the JVM

### ISSUE THREAD

**Issue by NicolasRouquette** [opencaesar/oml-luxor#20]
## Description

It is unclear how the extension finds a JVM to run the OML jar libraries.
If the extension uses an old JVM, then it fails repeatedly with errors like this:

```
[Trace - 11:12:09 AM] Sending request 'initialize - (0)'.
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: io/opencaesar/oml/dsl/ide/launch/OmlServerLauncher has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
[Info  - 11:12:09 AM] Connection to server got closed. Server will restart.
```

## Steps to Reproduce
- [ ] Step 1
- [ ] Step 2
- [ ] Step 3

## Expected Behavior
A clear and concise description of what should be the expected behavior.

## Additional Context
Enter any other details such as dependencies, environment, examples, etc.

## Relevant screenshots
If applicable, add screenshots to help illustrate the issue.

**Comment by LewisHumphries** [comment]
Hello, I'm currently having the same issue with trying to set a specific java version for the OML language server and was wondering if a solution was found for this.

**Comment by melaasar** [comment]
In your VS Code's terminal view, can you run `java -version` and see what version of Java is available. The extension requires at least Java 11 (which is class file 55). It appears you had Java 8 (class file version 52)?

**Comment by LewisHumphries** [comment]
That makes sense, is there any way to point the extension to a specific Java version, or can this only be done by changing the Java version my system uses?
